#!/bin/bash
#
# Use Open Office to reduce filesize, as the default optimisations are better than my scanner
#

function usage {
  echo "Usage:"
  echo "$0 [options]"
  echo
  echo "  -i <input_path>   Path to directory containing input files, default is '.'"
  echo "  -o <output_path>  Path to directory to write output files, default is './out/'"
  exit
}

INPUT_DIR=.
OUTPUT_DIR=./out

while getopts ":hi:o:" opt; do
  case ${opt} in
    h ) # Help
      usage
      ;;
    i ) # input_path
      INPUT_DIR=$OPTARG
      ;;
    o ) # output_path
      OUTPUT_DIR=$OPTARG
      ;;
    : )
      echo "invalid option: $OPTARG requires an argument" 1>&2
      usage
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      usage
      ;;
  esac
done

echo "Processing PDF files under '${INPUT_DIR}'"
echo "Output directory set to '${OUTPUT_DIR}'"
# Create the output directory if it doesn't exist
if [ ! -e "${OUTPUT_DIR}" ]; then
  echo "Output directory doesn't exist - creating as: '${OUTPUT_DIR}'"
  mkdir -p "${OUTPUT_DIR}"
fi
echo "=========="
echo

# Find PDF files under the specified input directory, and process them
#
# For an explanation of this while loop, see http://mywiki.wooledge.org/BashFAQ/020
while IFS= read -r -d $'\0' filename; do
  echo "Processing: ${filename}"
  echo "=========="

  # Mirror the input directory structure in the output file
  target_path=$(dirname "${OUTPUT_DIR}/${filename}")
  if [ -d "${target_path}" ]; then
    echo "Target Path Exists: ${target_path}"
  else
    echo "Creating Target Path: ${target_path}"
    mkdir -p "${target_path}"
  fi

  # Use soffice to recompress the pdf
  soffice --headless --convert-to pdf "${filename}" --outdir "${target_path}"

  echo
done < <(find "${INPUT_DIR}" -name "*.pdf" -not -path "${OUTPUT_DIR}/*" -print0)
